//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace monitor3lx.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("195.138.210.152")]
        public string SSHHost {
            get {
                return ((string)(this["SSHHost"]));
            }
            set {
                this["SSHHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aquila")]
        public string SSHusername {
            get {
                return ((string)(this["SSHusername"]));
            }
            set {
                this["SSHusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("moonspell")]
        public string SSHPassPharse {
            get {
                return ((string)(this["SSHPassPharse"]));
            }
            set {
                this["SSHPassPharse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Poliektov\\tmp\\sld\\vv_dev\\SshHostKeys\\aquila_sec_ssh.ppk")]
        public string SSHKeyFile {
            get {
                return ((string)(this["SSHKeyFile"]));
            }
            set {
                this["SSHKeyFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MTS3pg")]
        public string PGDatabese {
            get {
                return ((string)(this["PGDatabese"]));
            }
            set {
                this["PGDatabese"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("aq")]
        public string PGusername {
            get {
                return ((string)(this["PGusername"]));
            }
            set {
                this["PGusername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sql16384")]
        public string PGpass {
            get {
                return ((string)(this["PGpass"]));
            }
            set {
                this["PGpass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public int PGport {
            get {
                return ((int)(this["PGport"]));
            }
            set {
                this["PGport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15435")]
        public int PGlocalport {
            get {
                return ((int)(this["PGlocalport"]));
            }
            set {
                this["PGlocalport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT public.addmessage(\'monitor\', \'mts3\', \'i\')")]
        public string ApplyCommand {
            get {
                return ((string)(this["ApplyCommand"]));
            }
            set {
                this["ApplyCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int SSHPort {
            get {
                return ((int)(this["SSHPort"]));
            }
            set {
                this["SSHPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT public.addmessage(\'monitor\', \'mts3\', \'vol\')")]
        public string VolCommand {
            get {
                return ((string)(this["VolCommand"]));
            }
            set {
                this["VolCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TpFields {
            get {
                return ((string)(this["TpFields"]));
            }
            set {
                this["TpFields"] = value;
            }
        }
    }
}
